steps:   
  #Run Software Composition Analysis (SCA security scan) using Snyk
  - name: 'ubuntu'
    entrypoint: bash
    args: 
        - '-c'
        - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN=${_SNYK_TOKEN}
          export SNYK_TOKEN
          mvn snyk:test -fn 
    id: Snyk SCA
  #Execute SonarCloud Scan
   - name: maven:3-openjdk-18-slim
    entrypoint: mvn
    args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=sbarongo','-Dsonar.projectKey=sbarongo_wda-devsecops-demo','-Dsonar.token=${_SONAR_TOKEN}']
    id: SAST Scan using SonarCloud in GCP DevSecOps Pipeline
options:
  logging: CLOUD_LOGGING_ONLY